/**
 * Mock API Service
 * 
 * Simulates backend API responses for frontend development.
 * Will be replaced with real API client in Phase 2.
 * 
 * Version: 1.0.0
 * Date: November 14, 2024
 */

import type {
  ChatMessageRequest,
  ChatMessageResponse,
  ConversationsListResponse,
  ConversationDetailResponse,
  ConversationMessagesResponse,
  DeleteConversationResponse,
  Artifact,
  ChartArtifact,
  TableArtifact,
  ReportArtifact,
  DocumentArtifact,
} from '../types/api';

// ============================================================================
// MOCK DATA STORAGE
// ============================================================================

interface MockConversation {
  id: number;
  title: string;
  created_at: string;
  updated_at: string;
  messages: Array<{
    id: number;
    role: 'user' | 'assistant' | 'system';
    content: string;
    created_at: string;
    metadata?: {
      artifacts?: Artifact[];
    };
  }>;
}

let mockConversations: MockConversation[] = [];
let nextConversationId = 1;
let nextMessageId = 1;

// ============================================================================
// MOCK ARTIFACTS
// ============================================================================

const MOCK_CHART_ARTIFACT: ChartArtifact = {
  artifact_type: 'CHART',
  title: 'Digital Transformation Progress',
  description: 'Progress across key transformation initiatives',
  content: {
    chart: { type: 'bar' },
    title: { text: 'Digital Transformation Progress' },
    xAxis: {
      categories: ['Data Integration', 'Process Automation', 'AI Adoption', 'Cloud Migration'],
    },
    yAxis: {
      title: { text: 'Completion %' },
      min: 0,
      max: 100,
    },
    series: [
      {
        name: 'Progress',
        data: [85, 72, 45, 68],
        color: '#000000',
      },
    ],
  },
};

const MOCK_TABLE_ARTIFACT: TableArtifact = {
  artifact_type: 'TABLE',
  title: 'Government Entities - Transformation Status',
  description: 'Overview of transformation initiatives across entities',
  content: {
    columns: ['Entity', 'Initiatives', 'Completion %', 'Status', 'Budget (M SAR)'],
    rows: [
      ['Ministry of Interior', 12, 85, 'On Track', 450],
      ['Ministry of Health', 8, 72, 'On Track', 320],
      ['Ministry of Education', 15, 45, 'At Risk', 580],
      ['Ministry of Finance', 10, 90, 'Ahead', 410],
      ['Ministry of Transport', 6, 68, 'On Track', 290],
    ],
    total_rows: 5,
  },
};

const MOCK_REPORT_ARTIFACT: ReportArtifact = {
  artifact_type: 'REPORT',
  title: 'Q4 2024 Transformation Summary',
  description: 'Quarterly executive summary of cognitive transformation initiatives',
  content: {
    format: 'markdown',
    body: `# Q4 2024 Transformation Summary

## Executive Overview

The fourth quarter of 2024 demonstrated significant progress in our cognitive government transformation initiatives, with **72% overall completion** across all participating entities.

## Key Achievements

### Digital Infrastructure
- **85% completion** on data integration platform
- Successfully migrated 12 entities to cloud infrastructure
- Established AI governance framework

### Process Automation
- Automated 47 critical government processes
- Reduced average processing time by **63%**
- Citizen satisfaction score: **4.2/5**

### Challenges & Mitigation

**Challenge:** Slower than expected AI adoption in some entities
**Mitigation:** Enhanced training programs and change management support

**Challenge:** Budget constraints in Q1 2025
**Mitigation:** Prioritization framework implemented

## Next Quarter Priorities

1. Complete remaining cloud migrations
2. Launch citizen-facing AI services pilot
3. Expand automation to 30 additional processes
4. Conduct comprehensive security audit

## Budget Status

**Allocated:** 2.05B SAR  
**Spent:** 1.47B SAR (72%)  
**Remaining:** 580M SAR

---

*Report generated by JOSOOR Analytics Engine*
`,
  },
};

const MOCK_DOCUMENT_ARTIFACT: DocumentArtifact = {
  artifact_type: 'DOCUMENT',
  title: 'AI Governance Framework',
  description: 'Comprehensive framework for responsible AI deployment',
  content: {
    format: 'html',
    body: `
      <div style="font-family: Inter, sans-serif; padding: 24px;">
        <h1 style="font-size: 24px; font-weight: 600; margin-bottom: 16px;">AI Governance Framework</h1>
        
        <section style="margin-bottom: 24px;">
          <h2 style="font-size: 20px; font-weight: 600; margin-bottom: 12px;">1. Principles</h2>
          <ul style="line-height: 1.6; color: #6B7280;">
            <li><strong>Transparency:</strong> All AI systems must be explainable and auditable</li>
            <li><strong>Fairness:</strong> Prevent bias and ensure equitable outcomes</li>
            <li><strong>Privacy:</strong> Protect citizen data with highest standards</li>
            <li><strong>Accountability:</strong> Clear ownership and responsibility</li>
          </ul>
        </section>

        <section style="margin-bottom: 24px;">
          <h2 style="font-size: 20px; font-weight: 600; margin-bottom: 12px;">2. Implementation Requirements</h2>
          <ol style="line-height: 1.6; color: #6B7280;">
            <li>Risk assessment before deployment</li>
            <li>Regular audits and monitoring</li>
            <li>Citizen consent and opt-out mechanisms</li>
            <li>Data minimization and retention policies</li>
          </ol>
        </section>

        <section>
          <h2 style="font-size: 20px; font-weight: 600; margin-bottom: 12px;">3. Oversight Committee</h2>
          <p style="line-height: 1.6; color: #6B7280;">
            A cross-functional committee reviews all AI deployments quarterly and maintains 
            compliance with national and international standards.
          </p>
        </section>
      </div>
    `,
  },
};

// ============================================================================
// MOCK RESPONSES
// ============================================================================

const MOCK_RESPONSES: Record<string, ChatMessageResponse> = {
  default: {
    conversation_id: 1,
    message: "I'm Noor, your guide to JOSOOR — the Cognitive Transformation Bridge. I can help you explore transformation initiatives, analyze data, and navigate our platform. What would you like to know?",
    visualization: null,
    insights: [
      'JOSOOR connects traditional government operations with AI-powered transformation',
      'Access all content through conversational AI',
      'Supports both Arabic and English',
    ],
    artifacts: [],
  },
  chart: {
    conversation_id: 1,
    message: "Here's a visualization of our digital transformation progress across key initiatives. The data shows strong progress in data integration (85%) and cloud migration (68%), while AI adoption is still ramping up at 45%.",
    visualization: null,
    insights: [
      'Data integration leading with 85% completion',
      'AI adoption at 45% - opportunity for acceleration',
      'Overall transformation health: Strong',
    ],
    artifacts: [MOCK_CHART_ARTIFACT],
  },
  table: {
    conversation_id: 1,
    message: "This table shows the transformation status across government entities. Ministry of Finance is performing exceptionally well at 90% completion, while Ministry of Education needs attention at 45%.",
    visualization: null,
    insights: [
      '4 out of 5 entities on track or ahead',
      'Ministry of Education flagged for support',
      'Total budget utilization: 2.05B SAR',
    ],
    artifacts: [MOCK_TABLE_ARTIFACT],
  },
  report: {
    conversation_id: 1,
    message: "I've generated the Q4 2024 transformation summary report. Key highlights include 72% overall completion, 47 automated processes, and a 63% reduction in processing time.",
    visualization: null,
    insights: [
      '72% overall completion rate',
      '47 processes automated this quarter',
      '63% reduction in average processing time',
      'Citizen satisfaction: 4.2/5',
    ],
    artifacts: [MOCK_REPORT_ARTIFACT],
  },
  document: {
    conversation_id: 1,
    message: "Here's our comprehensive AI Governance Framework. It outlines the principles, implementation requirements, and oversight mechanisms for responsible AI deployment across government entities.",
    visualization: null,
    insights: [
      'Framework based on transparency, fairness, privacy, and accountability',
      'Mandatory risk assessment before deployment',
      'Quarterly oversight committee reviews',
    ],
    artifacts: [MOCK_DOCUMENT_ARTIFACT],
  },
  multi: {
    conversation_id: 1,
    message: "I've prepared a comprehensive analysis including progress charts, entity status table, and the quarterly report. This gives you a complete picture of our transformation landscape.",
    visualization: null,
    insights: [
      'Multi-dimensional view of transformation progress',
      'Combined quantitative and qualitative analysis',
      'Actionable recommendations included',
    ],
    artifacts: [MOCK_CHART_ARTIFACT, MOCK_TABLE_ARTIFACT, MOCK_REPORT_ARTIFACT],
  },
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

function delay(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function detectResponseType(query: string): keyof typeof MOCK_RESPONSES {
  const q = query.toLowerCase();
  
  if (q.includes('chart') || q.includes('graph') || q.includes('visualize') || q.includes('progress')) {
    return 'chart';
  }
  if (q.includes('table') || q.includes('list') || q.includes('entities') || q.includes('status')) {
    return 'table';
  }
  if (q.includes('report') || q.includes('summary') || q.includes('quarterly')) {
    return 'report';
  }
  if (q.includes('document') || q.includes('framework') || q.includes('governance') || q.includes('policy')) {
    return 'document';
  }
  if (q.includes('all') || q.includes('everything') || q.includes('complete') || q.includes('comprehensive')) {
    return 'multi';
  }
  
  return 'default';
}

function createMockConversation(title: string): MockConversation {
  const conv: MockConversation = {
    id: nextConversationId++,
    title,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    messages: [],
  };
  mockConversations.push(conv);
  return conv;
}

// ============================================================================
// API METHODS
// ============================================================================

export const mockApi = {
  /**
   * POST /api/v1/chat/message
   */
  async sendMessage(request: ChatMessageRequest): Promise<ChatMessageResponse> {
    await delay(800); // Simulate network delay

    // Find or create conversation
    let conversation = mockConversations.find(c => c.id === request.conversation_id);
    if (!conversation) {
      conversation = createMockConversation(request.query.slice(0, 50));
    }

    // Add user message
    conversation.messages.push({
      id: nextMessageId++,
      role: 'user',
      content: request.query,
      created_at: new Date().toISOString(),
    });

    // Determine response type
    const responseType = detectResponseType(request.query);
    const response = { ...MOCK_RESPONSES[responseType] };
    response.conversation_id = conversation.id;

    // Add assistant message
    conversation.messages.push({
      id: nextMessageId++,
      role: 'assistant',
      content: response.message,
      created_at: new Date().toISOString(),
      metadata: {
        artifacts: response.artifacts,
      },
    });

    conversation.updated_at = new Date().toISOString();

    return response;
  },

  /**
   * GET /api/v1/chat/conversations
   */
  async getConversations(): Promise<ConversationsListResponse> {
    await delay(300);

    return {
      conversations: mockConversations.map(c => ({
        id: c.id,
        title: c.title,
        message_count: c.messages.length,
        created_at: c.created_at,
        updated_at: c.updated_at,
      })),
    };
  },

  /**
   * GET /api/v1/chat/conversations/{id}
   */
  async getConversation(id: number): Promise<ConversationDetailResponse> {
    await delay(300);

    const conversation = mockConversations.find(c => c.id === id);
    if (!conversation) {
      throw new Error(`Conversation ${id} not found`);
    }

    return {
      conversation: {
        id: conversation.id,
        title: conversation.title,
        created_at: conversation.created_at,
        updated_at: conversation.updated_at,
        user_id: 1, // Demo user
      },
      messages: conversation.messages,
    };
  },

  /**
   * GET /api/v1/chat/conversations/{id}/messages
   */
  async getConversationMessages(id: number): Promise<ConversationMessagesResponse> {
    await delay(300);

    const conversation = mockConversations.find(c => c.id === id);
    if (!conversation) {
      throw new Error(`Conversation ${id} not found`);
    }

    return {
      messages: conversation.messages.slice(-100), // Last 100 messages
    };
  },

  /**
   * DELETE /api/v1/chat/conversations/{id}
   */
  async deleteConversation(id: number): Promise<DeleteConversationResponse> {
    await delay(300);

    const index = mockConversations.findIndex(c => c.id === id);
    if (index === -1) {
      throw new Error(`Conversation ${id} not found`);
    }

    mockConversations.splice(index, 1);

    return {
      success: true,
      message: `Conversation ${id} deleted successfully`,
    };
  },

  /**
   * Clear all mock data (for testing)
   */
  clearAll() {
    mockConversations = [];
    nextConversationId = 1;
    nextMessageId = 1;
  },
};
